version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      # Mount the app config to container in order to keep it outside the image
      - "./src/app/instance:/usr/src/app/src/app/instance"
